### ISSUE TITLE
Enable option for autologin on one provider

### ISSUE THREAD

**Issue by menardorama** [H2CK/oidc#143]
It could be great to have an autologin feature on your plugin like on SSO SAML Plugin.

We are using the SSO SAML app for now and would like to migrate to OIDC for easier setup but for now it does not seems possible with your plugin.

Do you think it could be possible to add this feature ?

Thanks

**Comment by H2CK** [comment]
What do you exactly mean? Are we talking about Integrated Windows Authentication (IWA) (https://learn.microsoft.com/en-us/aspnet/web-api/overview/security/integrated-windows-authentication)?

This feature would require that the oidc app also support NTLM / Kerberos towards the client and a capable Active Directory in the backend. This would be a very large extension. Since the app currently only 'speaks' OpenID Connect.
It from my perspective it might be easier to integrate the functionality of this app in the SSO SAML Plugin. So that SSO SAML Plugin is extended with the OpenID Connect protocol.

**Comment by menardorama** [comment]
No I was talking about the feature on SSO SAML Plugin that redirect automatically to the WebSOO when reaching the login page.

We only use SSO in my company and don't use plain login/password. 

Migrating to OIDC would be better for us as it is easier to maintain.
I our case we would have only one auth mechanism, so having an automatic redirect would make the behaviour the same as it is on all of our SSOized apps

**Comment by H2CK** [comment]
After some more analysis. So you would like to have the app extended not to use the Nextcloud user/authentication system as IdP (which is based on username/password) and allow the configuration of an own IdP like an Active Directory to also support e.g. non-username logins (As you can configure IdPs in the SSO SAML Plugin)?
