### ISSUE TITLE
Display name claim

### ISSUE THREAD

**Issue by madduck** [H2CK/oidc#257]
There seems to be no way to obtain the display name claim, and `name` just contains the user ID. It would be nice if that could be fixed.

**Comment by H2CK** [comment]
Current implementation works as following:

Claims `sub` and `preferred_username` contain the nextcloud user id. 

If the provided scope contains `email` additionally the claim `email` should be available, which contains the users email address. 

If the provided scope contains `profile` additionally the claim `name` is provided which contains the display name.
See: https://github.com/H2CK/oidc/blob/a43fe4887410148c35aeb721ad42b61e336fc8c2/lib/Controller/UserInfoController.php#L179

Maybe the display name is not set correctly on your nextcloud instance. It should already be provided in the claim `name`.
Since the code already tries to retrieve it via the method `getDisplayName` (e.g. https://stable19--nextcloud-server.netlify.app/classes/ocp-iuser#method_getDisplayName)
The description of this method states: _get the display name for the user, if no specific display name is set it will fallback to the user id_

**Comment by madduck** [comment]
The `oauth2` app gets the display name from Nextcloud alright and the other party can claim it with `ocs.data.display-name`, and that works fine.

I am using WikiJS, which doesn't seem to allow me to specify the scopes. Fact is that the `name` claim doesn't contain the display name.

I read your message to mean that `preferred_username` will also only get the user ID, not the display name.

I've got a test setup here, so happy to try things out.

**Comment by H2CK** [comment]
I did several tests today with the following results:
If a user has a display name set on the users profile page then the id token as well the user info contain the claim `name` and this claim itself contains the display name. If the display name is not set in the user profile, then the claim `name` just contains the user id.

I am not sure why you should not receive the display name in the id token or the user info.
From where did you try to retrieve the display name? From the id token or from the user info endpoint at `/index.php/apps/oidc/userinfo`?

**Comment by madduck** [comment]
@H2CK I am afraid you have to look at me as a complete beginner. I understand the concepts of OIDC, but not the details. I am just trying to get WikiJS to auth against Nextcloud right now. And this is how I have it configured:

![image](https://github.com/H2CK/oidc/assets/195073/41f87520-9989-4364-8353-247a327e0b06)

For the record, I am successfully using the `oauth2` app with the following configuration, and it does correctly return the display name:

![image](https://github.com/H2CK/oidc/assets/195073/2c42e591-7a20-40bb-9fda-1aa498ef7705)

Also, for completeness, here is my Nextcloud profile settings showing the full name:

![image](https://github.com/H2CK/oidc/assets/195073/c63bc4b7-db37-422e-8ea8-a11cb71f86d0)

My username is `martin.krafft` and this is what OIDC gets as the display name, i.e. fallback.

**Comment by H2CK** [comment]
Please try to correct your configuration in the following way:

- Correct your _User Info Endpoint URL_ to: ...apps/oidc/userinfo 
- Disable _Skip User Profile_

Maybe that helps.

**Comment by madduck** [comment]
That does work, thanks @H2CK. Closing this issue, you might still want to consider making the docs a bit more verbose. And I'll try to augment the WikiJS docs…
