### ISSUE TITLE
Do I need to do anything besides installing the app?

### ISSUE THREAD

**Issue by ninoppp** [H2CK/oidc#29]
Hey there
I'm trying to set up this app for matrix-synapse. However, it fails when trying to load metadata from the server, which means, it can't make a connection. 
I've installed the app and added matrix as a client. When visting the discovery endpoint via browser, it works. Does that mean, the issue is within synapse? Thanks for any help.

**Comment by H2CK** [comment]
As described in the documentation the discovery endpoint is provided at `/index.php/apps/oidc/openid-configuration`. The common path to this endpoint should be `/.well-known/openid-configuration`. Since this app cannot setup a redirect to this endpoint automatically for you, you have to configure a redirect by your own. Alternatively you have to configure the service (here: matrix-synapse) with a custom discovery endpoint.

As you can find in #5 this app works successfully with matrix-synapse. Maybe the example configuration in this issue will help you to configure matrix-synapse correctly.

**Comment by ninoppp** [comment]
Thanks, I now got it to work somewhat. However, now after loggin into nextcloud, when being redirected to matrix I get this error:
`2022-09-27 11:43:52,230 - synapse.handlers.oidc - 843 - ERROR - GET-37676 - Invalid id_token
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 840, in handle_oidc_callback
    id_token = await self._parse_id_token(token, nonce=session_data.nonce)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 718, in _parse_id_token
    claims.validate(leeway=120)  # allows 2 min of clock skew
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/authlib/oidc/core/claims.py", line 35, in validate
    self.validate_iss()
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/authlib/jose/rfc7519/claims.py", line 109, in validate_iss
    self._validate_claim_value('iss')
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/authlib/jose/rfc7519/claims.py", line 71, in _validate_claim_value
    raise InvalidClaimError(claim_name)
authlib.jose.errors.InvalidClaimError: invalid_claim: Invalid claim "iss"
	`
Error Text:
`invalid_claim: Invalid claim "iss"`
Have I set the "issuer" to something wrong? Doesn't issuer just need to be the base url of the nextcloud instance?

**Comment by H2CK** [comment]
The issuer and therefore the content in the claim iss is constructed in the app as following:
`$issuer = $this->request->getServerProtocol() . '://' . $this->request->getServerHost() . $this->urlGenerator->getWebroot();`
Therefore you are right it should be the base url of your nextcloud instance. But the function getServerHost() depends
on some conditions.
Either the issuer is not configured correctly in your matrix instance. Or the function getServiceHost might not return the current server host. See remarks at [PHP Documentation](https://www.php.net/manual/en/reserved.variables.server.php) for the server variables HTTP_HOST and SERVER_NAME. Nextcloud tries to determine the server host either from `HTTP_X_FORWARDED_HOST` following from `HTTP_HOST` or as last resort from `SERVER_NAME`.
That this works correctly you have to configure you web server correctly (see remark on Apache at SERVER_NAME).

**Comment by ninoppp** [comment]
Hmm I'm at a bit of a loss to be honest. The ServerName is set correctly, UseCanonicalName is on, the issuer in matrix is configured correctly, but I still get the wrong error. How can I see, what value is actually being sent as issuer?

**Comment by H2CK** [comment]
Currently the app doesn't log the generated issuer.  I will try to add the possibility to add some logging in the next version.

Alternatively on matrix side the log level might be increase that matrix is logging the claim iss. 

Further alternatives are:
- Logging of requests from matrix (the one which fetches the JWT)  and extracting the JWT from the Authorization Header. After that you can decode the JWT with e.g. jwt.io
- Use Postman and setup an oidc client for Postman. In Postman you configure Authentication accordingly so that you are able to retrieve the JWT and iss claim.

**Comment by H2CK** [comment]
In release [0.2.2](https://github.com/H2CK/oidc/releases/tag/0.2.2) there is now some logging in the app (debug level required) which outputs the some information (e.g. issuer) of the created JWT.

**Comment by ninoppp** [comment]
Oh god, I completely missed your answers, too much going on. Thanks a lot. How exactly can I use said app logging?

**Comment by ninoppp** [comment]
Thanks a lot for your answer. Finally got around to picking this up again. Unfortunately not getting very far, since the iss generated in the logs is exactly the issuer I set in matrix... yet I still get the same error... 
![image](https://user-images.githubusercontent.com/101364396/198155449-f18cbcaa-de96-4896-a5c6-d64f5c7a52ea.png)

**Comment by H2CK** [comment]
It is not clear for me why iss should be an invalid claim. Maybe there is some misconfiguration on synapse side. Could you check or provide your synapse configuration?

**Comment by ninoppp** [comment]
Okay problem solved, iss url had a slash at the end on one point in contrast to the other point. Arrrghhh.

Do you have a IBAN/Paypal/Whatever I can buy you a coffee at for maintaining the app and the support? Feel free to post or ping me nino.preuss@indiez.ch

**Comment by H2CK** [comment]
Nice to here the good news.

If you like to donate you could use the badge embedded in the [README.md](https://github.com/H2CK/oidc#nextcloud-oidc-app).
