### ISSUE TITLE
RedirectURI outside path of protected app

### ISSUE THREAD

**Issue by skug67** [H2CK/oidc#291]
I had been successfully using Nextcloud as an OIDC provider in front of Apache with mod_auth_openidc -- with multiple locations on the same server being protected.  At some point in the recent past (unfortunately, I can't pinpoint when) the setup stopped working.  I seem to be able to get it to work for a given location by setting the RedirectURI as a phony URL within that location (for example, if I'm protecting phpmyadmin at "https://my.server.tld/phpmyadmin" then a RedirectURI of "https://my.server.tld/phpmyadmin/callback" works fine.  But if instead I try to use "https://my.server.tld/oidc-protected" something goes wrong and I never successfully reach the intended page and instead get an "Object not found"

**Comment by H2CK** [comment]
The oidc for Nextcloud has no rules on how to handle redirect uris. If the redirect uri is configured and matches it will be accepted for the further processing.
Maybe there is some change in the apache extension module.
Otherwise if you think there is an error or misbehavior in the oidc app for Nextcloud, than please provide some more details like logs of Nextcloud with messages from oidc app. It helps to enable the debug level for logging in this case.

**Comment by skug67** [comment]
User error.  Somehow I changed the RedirectURI but not made the new location protected by mod_auth_openidc.  All is fine now.  Sorry for raising a flag when it was just my own stupidity.Sent from my iPadOn Oct 14, 2023, at 12:41 PM, H2CK ***@***.***> wrote:﻿
The oidc for Nextcloud has no rules on how to handle redirect uris. If the redirect uri is configured and matches it will be accepted for the further processing.
Maybe there is some change in the apache extension module.
Otherwise if you think there is an error or misbehavior in the oidc app for Nextcloud, than please provide some more details like logs of Nextcloud with messages from oidc app. It helps to enable the debug level for logging in this case.
