### ISSUE TITLE
Configuration with dovecot

### ISSUE THREAD

**Issue by mimi89999** [H2CK/oidc#46]
Hello,
I would like to setup Nextcloud as an XOauth2 backend for Dovecot https://doc.dovecot.org/configuration_manual/authentication/oauth2/, but I'm not quite sure how to do this. When adding a client in Nextcloud, I need to set the `Redirection URI`, but I have no clue what it should be.

**Comment by H2CK** [comment]
I am not aware how to use the app with Dovecot.
The Redirection URI is the address to which the user is redirected after a successfull login at the Nextcloud Instance. This should be some address pointing to your Dovecot server. I would expect that this redirect url can be found in the Dovecot docuentation.

**Comment by H2CK** [comment]
Dovecot is act as pure OAuth Resource Server. Using OAuth with Dovecot requires a client which fetches the JWT token. This client (e.g. webmail client) will define the Redirect URI. Dovecot will just try to validate the received token using possibly the introspection endpoint.

The introspection endpoint is currently not supported by this app. 

But you could use the local JWT validation as defined in the documentation `introspection_mode = local`.
```
## How introspection is made, valid values are
##   auth = GET request with Bearer authentication
##   get  = GET request with token appended to URL
##   post = POST request with token=bearer_token as content
##   local = Attempt to locally validate and decode JWT token
# introspection_mode = auth
```

Answering your initial question: The `Redirection URI` depends on your client of Dovecot, which fetches the JWT.

**Comment by hirsm** [comment]
As @H2CK stated, you need to configure an OAuth2-client in the first place (e. g. Roundcube). Then, you need to configure dovecot with a second password backend pointing to OAuth2 (in `dovecot.conf`) so that you can authenticate against dovecot using the OAuth2 token:

`passdb {
  driver = oauth2
  mechanisms = xoauth2 oauthbearer
  args = /etc/dovecot/dovecot-oauth2.conf.ext
}`

In `dovecot-oauth2.conf.ext` file you need to set the data as follows:
`tokeninfo_url = https://cloud.blackdott.de/index.php/apps/oidc/userinfo?access_token=
introspection_url = https://cloud.blackdott.de/index.php/apps/oidc/userinfo
introspection_mode = auth
username_attribute = preferred_username`

Postfix needs to be configured to accept SASL login (assuming postfix uses dovecot's authentication stuff). Add to your `main.cf`:
`smtpd_relay_restrictions = $smtpd_relay_restrictions permit_sasl_authenticated
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes`

I think this should be it. At least it works for me (; As far as I remember, the order of the arguments of `smtpd_relay_restrictions` matters, so maybe you shouldn't add `permit_sasl_authenticated` after a `reject_unauth_destination`

**Comment by skug67** [comment]
Tried this, but the XOAUTH2 login w/dovecot fails.  (It works fine w/keycloak)

**Comment by H2CK** [comment]
Did you use introspection_mode = local with further configuration on checking necessary claims.
Dovecot per default uses an introspection endpoint which is currently not supported by the oidc app (Keycloak does support this). But if you configure local introspection it should work.

I will check if an introspection endpoint could be provided by the oidc app easily.

**Comment by skug67** [comment]
Thanks.  In fact when I turned on debugging I realized that the problem was a mismatch between username and email that I was able to solve by changing the username_attribute field.
