### ISSUE TITLE
Bug: redirect URIs broken when Nextcloud running in a subdirectory

### ISSUE THREAD

**Issue by darkphoenix** [H2CK/oidc#53]
It appears that the /index.php/apps/oidc/{authorize,redirect,etc} URLs are hardcoded to refer to the root.  This breaks redirecting for my setup where the install is (for historical reasons; I've been running this instance for years and years across various domains and hosts) at /nextcloud/, not the root.  It seems like an easy fix to just read the proper path from either config data or the referrer in some form, no?  For the time being I'm attempting to work around it by answering every hit to a URL under /index.php/apps/oidc with a 307 that should(tm) retain any POST body, if things go well.  I'll report back whether or not it works.  If I'm doing something stupid wrong here, feel free to tell me - but a brief search of the code makes it look like at least some bits of JS definitely have hardcoded paths in them...

**Comment by H2CK** [comment]
I am not sure if I got you right. 

I checked the code and there is one place in LoginRedirectorController.php where there might be an issue with a hardcoded path. I assume this breaks the login process (After successful login). Since every redirect after login goes to /index.php/apps/oidc/redirect (The redirect does not make use of the configured webfoot). I will fix this to also use the configured web root.

But in all other cases of url generation in the app e.g. generated urls in token the configured webroot of nextcloud is taken into account. And if you are not able to access the endpoints at the location `http(s)://your-domain/<your-webroot>/index.php/apps/oidc/...` then I would assume your webroot configuration might not be correct. This is something the Nextcloud router controls and not the app itself.

**Comment by H2CK** [comment]
The previously described change is introduced with version 0.1.11.

**Comment by selaux** [comment]
Would it be possible to use [`$this->urlGenerator->linkTo`](https://github.com/nextcloud/server/blob/master/lib/private/URLGenerator.php#L143) instead of the hardcoded path? With the "pretty" URLs in Nextcloud the path should be `/apps/oidc/redirect` (without the `index.php` part). This should not necessarily be a problem, as the links that include `index.php` should still work, but in my case the login page is broken and throws `The requested uri(/login) cannot be processed by the script '/index.php/login?redirect_url=/index.php')` for some reason. This error seems to be gone if I omit the `index.php` part from the `redirect_url` parameter which `linkTo` seems to do.

**Comment by H2CK** [comment]
I found the code part which prohibits to use the app when Nextcloud is accessible in a subdirectory.
I am working on a fix.

**Comment by selaux** [comment]
With `0.24` at least my issue is fixed. But I don't have the subdirectory configuration, just the pretty URLs. Thanks!
