### ISSUE TITLE
Nextcloud in a subdirectory: openid-configuration returns wrong endpoints

### ISSUE THREAD

**Issue by Larx** [H2CK/oidc#69]
As I don't use my OIDC protected drawers every day, I don't know when the following behaviour first appeared. 
I can no longer access those sites, logging in always redirects to my Nextcloud instance (which is installed in a subdirectory). Looking at the openid-configuration page, it seems that the issuer contains the subdirectory, and the endpoints are also including the path, so in the end the path is doubled. As Nextcloud does not know these pages, it defaults to its standard page.

![Bildschirmfoto vom 2022-10-21 17-27-49](https://user-images.githubusercontent.com/3582007/197245540-c5fce539-e4cb-41c2-9988-a7e959a50b38.png)

**Comment by H2CK** [comment]
The wrong links to the endpoint should be fixed with version 0.2.6. Hopefully it works now also for you.

If the Nextcloud instance runs in a subdirectory it is common that the issuer contains the subdirectory (webroot) to allow a hosting of multiple instances. (This is comparable to the different realms which could be configured e.g. in Keycloak)

**Comment by Larx** [comment]
Works again after the update, thanks.
